---

- name: Check if Wordpress CLI has been installed previously
  stat:
    path: '{{ wp_cli_destination }}'
  register: wp_cli

- name: Download Wordpress CLI
  get_url:
    url: '{{ wp_cli_download_url }}'
    dest: '{{ wp_cli_destination }}'
    mode: 0755
  when: not wp_cli.stat.exists
